/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FoundationRouteImport } from './routes/foundation'

const FoundationRoute = FoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/foundation': typeof FoundationRoute
}
export interface FileRoutesByTo {
  '/foundation': typeof FoundationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/foundation': typeof FoundationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/foundation'
  fileRoutesByTo: FileRoutesByTo
  to: '/foundation'
  id: '__root__' | '/foundation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  FoundationRoute: typeof FoundationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/foundation': {
      id: '/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof FoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  FoundationRoute: FoundationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
