/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as FoundationRouteImport } from './routes/foundation'
import { Route as IndexRouteImport } from './routes/index'

const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationRoute = FoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foundation': typeof FoundationRoute
  '/intelligence': typeof IntelligenceRoute
  '/mission-control': typeof MissionControlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foundation': typeof FoundationRoute
  '/intelligence': typeof IntelligenceRoute
  '/mission-control': typeof MissionControlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foundation': typeof FoundationRoute
  '/intelligence': typeof IntelligenceRoute
  '/mission-control': typeof MissionControlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/foundation' | '/intelligence' | '/mission-control'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/foundation' | '/intelligence' | '/mission-control'
  id: '__root__' | '/' | '/foundation' | '/intelligence' | '/mission-control'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoundationRoute: typeof FoundationRoute
  IntelligenceRoute: typeof IntelligenceRoute
  MissionControlRoute: typeof MissionControlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundation': {
      id: '/foundation'
      path: '/foundation'
      fullPath: '/foundation'
      preLoaderRoute: typeof FoundationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoundationRoute: FoundationRoute,
  IntelligenceRoute: IntelligenceRoute,
  MissionControlRoute: MissionControlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
